### ISSUE TITLE
WLED WiFi fails when /win&RD=0 command sent to it

### ISSUE THREAD

**Issue by GarSys** [Aircoookie/WLED#1037]
**Describe the bug**
When I execute:
    action: call-service
    service: rest_command.hyperion_tv_off 
the wifi connection of the Wemos D1 Mini crashes and the only way to bring it back online is to power cycle the Wemos D1 Mini.  This happens whether it is in override mode (from the web interface) or not.

**To Reproduce**
In Home Assistant:
```
rest_command:
  hyperion_tv_on:
    url: 'http://192.168.17.159/win&RD=1'
  hyperion_tv_off:
    url: 'http://192.168.17.159/win&RD=0'

sensors.yaml:
- platform: rest
  name: Hyperion TV
  resource: http://192.168.17.159/json/info
  value_template: '{{ value_json.live }}'
  force_update: true
  device_class: illuminance

```
SIMPLEST WAY TO SEE THE PROBLEM:
Just send the http://192.168.17.159/win&RD=0 command via your browser.  The WiFi connection will then fail. Of, course, change the IP to where you have WLED running :) 

**Expected behavior**
The goal is to be able to change the source (WLED or Hyperion) that drives the LEDs (no crash when /win&RD=0 is sent).  Also to get feedback from WLED as to which state the ".live" parameter is (thus keeping Home Assistant current with WLED).

**WLED version**
 - Board: Wemos D1 Mini, (and ESP32 dev)
 - Version: "Namigai", Build 2005030
 - Environment: esp8266 2_6_3 (1)
 - Format:  Binaries from main GitHub site

**Additional context**
I have swapped out the Wemos Di Mini with an esp32 board and with a nodemcu (8266) board with the same sad results.

Thank you for your help!

**Comment by jes1417** [comment]
I use this in my HA switch.yaml and it works perfectly for turning off and on live data from Hyperion.


````
  - platform: rest
    name: WLED Hyperion Toggle
    resource: http://192.168.1.193/json/state
    body_on: '{"lor": 0}'
    body_off: '{"lor": 1}'
    is_on_template: '{{value_json.lor == 0}}'
    headers:
      Content-Type: application/json
````
