### ISSUE TITLE
Long reaction time with IR Sensor KY-022

### ISSUE THREAD

**Issue by AWSb24** [Aircoookie/WLED#2380]
### What happened?

By pressing any button on my 24 key remote several times until the ESP8266 changes color or switches on or off.

### To Reproduce Bug

I connected the IR sensor to GPIO4, 5, and 12. There is no change in behavior.

### Expected Behavior

Immediate reaction

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.0-b5

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

I comparing ESPHome with a self-writing config YAML with WLED.
I also flashed ESPHome on the same device to check whether it is an electronic or software issue.
On ESPHome it works flawlessly.

Yaml segment for on button in ESPHome for NEC remote command:
```
  - platform: remote_receiver
    id: "onbutton"
    nec:
      address: 0x00F7
      command: 0xC03F
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
