### ISSUE TITLE
Police effect removed?

### ISSUE THREAD

**Issue by jeroen85** [Aircoookie/WLED#3093]
### What happened?

I have my WLED connected to Home Assistant. Some automations make use of the `Police` effect (in combination with my audio setup playing Fireman Sam ;-) , my son loved it)

With the current version WLED 0.14.0-b1 "Hoshi", I am not able to use the police effect anymore.
It is removed? I don't see any 'Breaking Changes' within the release notes.

Can it be restored somehow?

### To Reproduce Bug

Run HA service
```
      - service: light.turn_on
        target:
          entity_id: light.ledstrip_tv
        data:
          effect: Police
          brightness: 255
```

### Expected Behavior

Enjoy the red/blue police light effect.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
