### ISSUE TITLE
Setting value for "Percent" effect changes preset to "unknown"

### ISSUE THREAD

**Issue by andreas-bulling** [Aircoookie/WLED#4471]
### What happened?

I have created a preset "soc" that uses the effect "Percent" for part of a LED strip to show our car's state of charge. The value I set in Home Assistant using

```
action: select.select_option
metadata: {}
data:
  option: soc
target:
  entity_id: select.wled_kitchen2_preset

action: number.set_value
data:
  value: "{{ states('sensor.car_battery') }}"
target:
  entity_id: number.wled_kitchen2_intensity
```

I noticed that while the selected preset is properly shown in Home Assistant after the first command, the second command makes wled change the preset to "unknown".

I am not sure if this is a bug but it's definitely not nice, at least not for the "Percent" effect (and potentnially others) because that's exactly what this effect is supposed to do. 

### To Reproduce Bug

see above

### Expected Behavior

The preset stays the same, even if the value/data/intensity is changed.

### Install Method

Binary from WLED.me

### What version of WLED?

0.15.0 build 2412100

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
