### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by Shaegi** [Aircoookie/WLED#99]
Im trying to write a full feature wled home assitant lovelace card.

To do so I need to request the current status of the wled onload of the page. Since WLED doesn't send the right CORS headers or has no option to do so I needed to install a chrome plugin to disable CORS protection. 
Since this doesnt seem like a good workaround it would be great if you could add CORS Headers (with an option) to the api responses. 

Thanks!

**Comment by Aircoookie** [comment]
Hi! I did some quick research and it seems like there are multiple CORS headers. Could you provide me with an example of the response headers and their contents you'd need for your application to work? Thanks!

**Comment by Shaegi** [comment]
Thanks for the quick response. Unfortunatly im not a CORS-expert.
At the moment im getting this error message 
`Access to fetch at 'http://[wled-ip]/win' from origin 'http://hassio.local:8123' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

According to https://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work a "Access-Control-Allow-Origin: * "-header would help. (maybe instead of * there could be a origin URL as option in wled settings?)

**Comment by rjhllr** [comment]
what worked for me in similar contexts were two things:
- the webserver should respond w/ HTTP 200 OK for preflight Requests (OPTIONS request verb)
- response should include the aforementioned "Access-Control-Allow-Origin" header.
Fortunately it's quite easy to debug, just open a codepen or a local domain and try to send an XHR request to the source, it will be blocked by CORS and you can then see why in the dev tools.

**Comment by aidbish** [comment]
@Shaegi Would you mind sharing your config for adding to Home Assistant. Also the Lovelace card would be a fantastic addition when complete

**Comment by Shaegi** [comment]
Sure thing. You can find the card on my github page. I will add some further information to install it. 

To add it as an odlschool entity light the configuration would be something like
As a lightcard this will give you control for brightness, effect and primary color 
```
light:
  - platform: mqtt
    name: 'WLED LED Strip'
    command_topic: "wled/1"
    brightness_command_topic: "wled/1"
    effect_command_topic: "wled/1/api"
    brightness_state_topic: "wled/1/g"
    rgb_state_topic: "wled/1/c"
    rgb_command_topic: "wled/1/col"
    rgb_command_template: "#{{ '%02x%02x%02x' | format(red, green, blue)}}"
    retain: true
    rgb: true
    effect_list: 
    - FX=0
    - FX=1
    - FX=2
    - FX=3
    - FX=4
    - FX=5
    - FX=6
    - FX=11
    - FX=68
    - FX=25
    - FX=60
    - FX=75
````

(you would need to add all effects)
